export enum Page {
    LANDING = "LANDING",
    GET_API_KEY = "GET_API_KEY",
    API_KEY_DETAIL = "API_KEY_DETAIL",
    HELP = "HELP",
    NFTS_MINTED = "NFTS_MINTED",
    NFTS_LAZY = "NFTS_LAZY",
    PREFERENCES = "PREFERENCES"
}
