<?php
/* This file was automatically generated by the `grunt libs:cachebuster` command (Mon Nov 08 2021 13:06:49 GMT+0100 (Central European Standard Time)). */
return array(
	'src/public/dist/admin.js' => '91676d9e5af4f8ad7beeb660744b8c3f',
	'src/public/dist/vendor-admin.js' => '3a0de1fe5709d597975e4e6993e9600a',
	'src/public/dist/vendor-widget.js' => '9ff81506ca9c5bab6a0d82f291de48e5',
	'src/public/dist/widget.js' => '5843d40216b9ed6a593acc0d642ea057',
	'src/public/dist/admin.css' => '10973535e145c79614a0946f3276902a',
	'src/public/dist/widget.css' => '1479e83e34ea80c5596ab0fa32dfa6e5',
	'src/public/dev/admin.js' => 'aa6ac1936fbde4cc340ec6ce95051755',
	'src/public/dev/i18n-dir/admin.js' => 'aa6ac1936fbde4cc340ec6ce95051755',
	'src/public/dev/i18n-dir/widget.js' => '213bf94a4473c0e927e049e2e7433b8e',
	'src/public/dev/vendor-admin.js' => 'dbeeee2042c016652466f3e1da318fa8',
	'src/public/dev/vendor-widget.js' => '4a976f7e2bc6ef2a9c5fd4c6bfe1ce50',
	'src/public/dev/widget.js' => '87376d314a9b6e955480c6869912adfb',
	'src/public/dev/admin.css' => '4db6ca18ab279b3befdfaf452a929820',
	'src/public/dev/widget.css' => '1479e83e34ea80c5596ab0fa32dfa6e5',
);
