<?php
/* This file was automatically generated by the `grunt libs:cachebuster` command (Tue Nov 23 2021 18:54:55 GMT+0000 (Coordinated Universal Time)). */
return array(
	'src/public/dist/admin.js' => '8b4434a06c26f543c93c6cd61acbbdcb',
	'src/public/dist/vendor-admin.js' => '544a5b292e9bff3de00321a3d11b0984',
	'src/public/dist/vendor-widget.js' => '9e3cdc863b954ff97d9e44bdb8f0384a',
	'src/public/dist/widget.js' => '55dc633ed835f64258416aab9b31c9dc',
	'src/public/dist/admin.css' => '171a52746ca0ae79e591dd7535306dc5',
	'src/public/dist/widget.css' => '1479e83e34ea80c5596ab0fa32dfa6e5',
);
