<?php
/* This file was automatically generated by the `grunt libs:cachebuster` command (Wed Nov 10 2021 15:04:14 GMT+0000 (Coordinated Universal Time)). */
return array(
	'mobx' => '4.15.4',
	'react' => '17.0.2',
	'react-dom' => '16.13.1'
);
