<?php
/* This file was automatically generated by the `grunt libs:cachebuster` command (Wed Nov 10 2021 15:04:14 GMT+0000 (Coordinated Universal Time)). */
return array(
	'src/public/dist/admin.js' => 'dd8e94fb001cfe80aad8f29094ce21ea',
	'src/public/dist/vendor-admin.js' => '31c3589a49274eb75bb33339be2e70bf',
	'src/public/dist/vendor-widget.js' => '9e3cdc863b954ff97d9e44bdb8f0384a',
	'src/public/dist/widget.js' => '274fb8b2176af1d74045c658f7f017c2',
	'src/public/dist/admin.css' => 'c4a8d332c1f204322552bb90d5490e91',
	'src/public/dist/widget.css' => '1479e83e34ea80c5596ab0fa32dfa6e5',
);
